### ISSUE TITLE
Fails after some time

### ISSUE THREAD

**Issue by jasperbom** [custom-components/sensor.untapped#12]
Initially everything worked fine but now I'm getting:

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/untappd.py", line 60, in setup_platform
    add_devices([UntappdCheckinSensor(username, api_id, api_secret)])
  File "/home/homeassistant/.homeassistant/custom_components/sensor/untappd.py", line 81, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/sensor/untappd.py", line 86, in update
    self._apisecret, self._username)
  File "/srv/homeassistant/lib/python3.5/site-packages/pyuntappd/__init__.py", line 26, in get_last_activity
    activity = get_last_activity['response']['checkins']['items'][0]
TypeError: list indices must be integers or slices, not str
```
Can anybody help me with this?

**Comment by iantrich** [comment]
Probably want to check that your client secret hasn't expired, or maybe you haven't used it so long that there is no activity?
