### ISSUE TITLE
Error with .0.94

### ISSUE THREAD

**Issue by priusweok** [custom-components/sensor.untapped#22]
I get the below error in my log after upgrading to .0.94.  It was working fine for me with .0.93.2.  I'm using v0.1.5 of Untapped

```
Error while setting up platform untappd
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/untappd/sensor.py", line 64, in setup_platform
    add_devices([UntappdCheckinSensor(username, api_id, api_secret)])
  File "/config/custom_components/untappd/sensor.py", line 70, in __init__
    from pyuntappd import Untappd
ModuleNotFoundError: No module named 'pyuntappd'
```

**Comment by swetoast** [comment]
Seems that it didnt install the pyuntappd  lib thats needed try reinstalling the untappd component again

**Comment by priusweok** [comment]
Looks like I was missing the manifest.json in my untapped folder.  I added that and rebooted.  Everything is working fine now.  Thanks!
