### ISSUE TITLE
Error while setting up untappd platform for sensor

### ISSUE THREAD

**Issue by sembeek** [custom-components/sensor.untapped#28]
Hi,

I'm receiving the following error in Home Assistant.
The entities aren't created.
This is my config:
```
sensor:
  - platform: untappd
    username: XXXXX
    id: XXXXXXX
    secret: XXXXX
```
And here is my log:
```
Error while setting up untappd platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/untappd/sensor.py", line 64, in setup_platform
    add_devices([UntappdCheckinSensor(username, api_id, api_secret)])
  File "/config/custom_components/untappd/sensor.py", line 85, in __init__
    self.update()
  File "/config/custom_components/untappd/sensor.py", line 89, in update
    result = self._untappd.get_last_activity(self._apiid,
  File "/usr/local/lib/python3.8/site-packages/pyuntappd/__init__.py", line 26, in get_last_activity
    activity = get_last_activity['response']['checkins']['items'][0]
KeyError: 'checkins'
```
I hope you can help me.

Thanks in advance!

**Comment by petreef** [comment]
Running into the same problem.
Error on the Sensor

**Comment by Bl3rp** [comment]
Same error unfortunately.

Error while setting up untappd platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/untappd/sensor.py", line 64, in setup_platform
    add_devices([UntappdCheckinSensor(username, api_id, api_secret)])
  File "/config/custom_components/untappd/sensor.py", line 85, in __init__
    self.update()
  File "/config/custom_components/untappd/sensor.py", line 89, in update
    result = self._untappd.get_last_activity(self._apiid,
  File "/usr/local/lib/python3.8/site-packages/pyuntappd/__init__.py", line 26, in get_last_activity
    activity = get_last_activity['response']['checkins']['items'][0]
KeyError: 'checkins'

**Comment by iantrich** [comment]
Just do a single check in on Untappd and you should be fine

**Comment by arjanvroege** [comment]
I'm having the same error after adding the custom component and after adding the sensor to the configuration. My account has already a lot of checkins and I've done one after adding the component but the error stays the same:

Error while setting up untappd platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/untappd/sensor.py", line 64, in setup_platform
    add_devices([UntappdCheckinSensor(username, api_id, api_secret)])
  File "/config/custom_components/untappd/sensor.py", line 85, in __init__
    self.update()
  File "/config/custom_components/untappd/sensor.py", line 89, in update
    result = self._untappd.get_last_activity(self._apiid,
  File "/usr/local/lib/python3.8/site-packages/pyuntappd/__init__.py", line 26, in get_last_activity
    activity = get_last_activity['response']['checkins']['items'][0]
KeyError: 'checkins'

**Comment by swetoast** [comment]
drink a beer cause your at 0, there isnt anything for it to scrape

**Comment by arjanvroege** [comment]
So that I understand it correctly I just need to drink (or add another beer).. Should other sensors be available in HA already because none of the sensors are inside HA at this moment. Or will other sensors become available after checking in another beer?

**Comment by swetoast** [comment]
yeah there has to be one beer checked in to the account then it works

**Comment by arjanvroege** [comment]
Still strange that existing checkins (before adding the component to HA) on my account are not counted. But yet another good reason to drink a beer ;-)

**Comment by arjanvroege** [comment]
I've still the same issue after checking in some beers to my untappd account. On the dashboard I can see that the sensor is contacting the API after the restart of HA. But the sensor is not going to work. What information do I need to share to investigate?
