### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by Naesstrom** [custom-components/sensor.untapped#35]
## Version of Home Assistant and installation type
core-2021.8.3

## Version of the custom_component

0.1.6

## Configuration

```yaml
sensor:
  - platform: untappd
    username: Naesstrom
    id: !secret untappd_ID
    secret: !secret untappd_Secret

### Templating for the untappd lovelace card (https://sharethelove.io/picture-elements-cards/untappd-card)
  - platform: template
    sensors:
      untappd_badge:
       value_template: "Recent Badge: {{ states.sensor.untappd_last_badge_naesstrom.attributes.badge }} (Level {{ states.sensor.untappd_last_badge_naesstrom.attributes.level }})"

  - platform: template
    sensors:
      untappd_beer:
       value_template: "Recent Beer: {{ states.sensor.untappd_last_check_in_naesstrom.attributes.beer }} ({{ states.sensor.untappd_last_check_in_naesstrom.attributes.abv }})"

  - platform: template
    sensors:
      untappd_followings:
#       unit_of_measurement: followers
       value_template: "{{ states.sensor.untappd_last_check_in_naesstrom.attributes.followings }}"
       entity_picture_template: "https://www.shareicon.net/data/32x32/2016/09/23/833751_people_512x512.png"

  - platform: template
    sensors:
      untappd_checked:
#       unit_of_measurement: checkins
       value_template: "{{ states.sensor.untappd_last_check_in_naesstrom.attributes.checkins }}"
       entity_picture_template: "https://www.shareicon.net/data/128x128/2015/05/30/46550_check_32x32.png"

  - platform: template
    sensors:
      untappd_total_beers:
#       unit_of_measurement: beers
       value_template: "{{ states.sensor.untappd_last_check_in_naesstrom.attributes.total_beers }}"
       entity_picture_template: "https://www.shareicon.net/data/32x32/2016/09/26/834858_drink_512x512.png"


  - platform: template
    sensors:
      untappd_total_badges:
#       unit_of_measurement: badges
       value_template: "{{ states.sensor.untappd_last_check_in_naesstrom.attributes.total_badges }}"
       entity_picture_template: "https://www.shareicon.net/data/32x32/2016/07/10/794103_miscellaneous_512x512.png"

```

## Debug log

```text
Logger: homeassistant.components.sensor
Source: custom_components/untappd/sensor.py:94
Integration: Sensor (documentation, issues)
First occurred: August 12, 2021, 5:20:05 PM (1 occurrences)
Last logged: August 12, 2021, 5:20:05 PM

Error while setting up untappd platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/untappd/sensor.py", line 67, in setup_platform
    add_devices([UntappdCheckinSensor(username, api_id, api_secret)])
  File "/config/custom_components/untappd/sensor.py", line 90, in __init__
    self.update()
  File "/config/custom_components/untappd/sensor.py", line 94, in update
    result = self._untappd.get_last_activity(
  File "/usr/local/lib/python3.9/site-packages/pyuntappd/__init__.py", line 26, in get_last_activity
    activity = get_last_activity['response']['checkins']['items'][0]
TypeError: list indices must be integers or slices, not str

Logger: homeassistant.helpers.template
Source: helpers/template.py:1417
First occurred: August 12, 2021, 5:20:13 PM (16534 occurrences)
Last logged: 3:15:01 PM

Template variable error: 'None' has no attribute 'attributes' when rendering 'Recent Beer: {{ states.sensor.untappd_last_check_in_naesstrom.attributes.beer }} ({{ states.sensor.untappd_last_check_in_naesstrom.attributes.abv }})'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.untappd_last_check_in_naesstrom.attributes.followings }}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.untappd_last_check_in_naesstrom.attributes.checkins }}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.untappd_last_check_in_naesstrom.attributes.total_beers }}'
Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.untappd_last_check_in_naesstrom.attributes.total_badges }}'

```

**Comment by swetoast** [comment]
Got a beer checked in?

**Comment by Naesstrom** [comment]
Yup, it was working fine earlier but stopped a few versions back!
![image](https://user-images.githubusercontent.com/6575206/129456184-2a255639-8fa7-49dd-b44c-f19830d23f9d.png)

**Comment by swetoast** [comment]
atten @iantrich 

sorry not really focusing on ha atm got my focus on steamlink with valve

**Comment by icemouton** [comment]
Having the same issue, anyone found a fix ?

**Comment by swetoast** [comment]
https://github.com/custom-components/sensor.untappd/issues/38#issuecomment-1112081446

Seems untappd is moving away from an open api to pay to play api
